### PR TITLE
A few fixes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by dysk0 — APPROVED** [review]

**Review by dysk0 — APPROVED** [review]

**Review by dysk0 — APPROVED** [review]

**Review by dysk0 — APPROVED** [review]

**Review by dysk0 — APPROVED** [review]

**Comment by dysk0** [comment]
I had an issue with merging so I have copied over changes manually. Sorry :)

**Comment by ghost** [comment]
Dysk0, i just downloaded the lasted version from Openrepo, but the broken translation link is still there as i have remove it so something went wrong with the merge....I will fix it again.

**Comment by ghost** [comment]
This is broken link or you fix the link to the correct transiflex page, or mebay you need to remove it as i had done it before.

        PullDownMenu {
            MenuItem {
                text: qsTr("Translate App")
                onClicked: Qt.openUrlExternally("https://www.transifex.com/gmax/pingviini/")
            }
}

**Comment by dysk0** [comment]
Hi, 
I'll update it to the https://www.transifex.com/dysko/pingviini/

Tnx :)

**Comment by ghost** [comment]
Hi,

I think there is 1 bugs i found when you like something the star will not updated....

**Comment by dysk0** [comment]
Tnx. Just create a ticket and I'll check.

**Pull request closed without merging**
